views:
  - title: Home
    sections:
      - type: grid
        cards:
          - type: heading
            icon: mdi:solar-power-variant
            heading: Vorschau
            heading_style: title
          - type: gauge
            entity: input_number.solar_heute_qualitat
            min: -10
            max: 10
            needle: true
            severity:
              green: 5
              yellow: -5
              red: -10
            tap_action:
              action: none
            grid_options:
              columns: 4
              rows: 3
          - type: gauge
            entity: input_number.solar_morgen_qualitat
            min: -10
            max: 10
            needle: true
            severity:
              green: 5
              yellow: -5
              red: -10
            tap_action:
              action: none
            grid_options:
              columns: 4
              rows: 3
          - type: gauge
            entity: input_number.solar_ubermorgen_qualitat
            min: -10
            max: 10
            needle: true
            severity:
              green: 5
              yellow: -5
              red: -10
            tap_action:
              action: none
            grid_options:
              columns: 4
              rows: 3
          - type: custom:mushroom-template-card
            primary: |
              Heute
            secondary: "{{ states.sensor.energy_production_today_remaining.state |\_round(2)}} kWh"
            icon: ''
            grid_options:
              columns: 4
              rows: 1
          - type: custom:mushroom-template-card
            primary: |
              Morgen
            secondary: "{{ states.sensor.energy_production_tomorrow.state |\_round(2) }} kWh"
            icon: ''
            grid_options:
              columns: 4
              rows: 1
          - type: custom:mushroom-template-card
            primary: |
              Übermorgen
            secondary: '{{ states.sensor.energy_production_d2.state| round(2)}} kWh'
            icon: ''
            grid_options:
              columns: 4
              rows: 1
    type: sections
    max_columns: 1
    cards: []
